### ISSUE TITLE
pattern ignorecase

### ISSUE THREAD

**Issue by aldum** [magyarchan/lulzbot#12]

**Comment by ShadowPhrogg32642342** [comment]
bot.py:119                if any(re.search(pattern.pattern, e.source.nick, flags=re.IGNORECASE) for pattern in user.patterns):

szerintem ez mar akkor sem volt issue amikor felvetted

yup:
> commit 54337f8ac4ac9a6bb9bb20bc7f3234a6f7aa4d3d
> Author: redacted <redacted>
> Date:   Mon Feb 17 13:26:29 2014 +0100
> 
>     -csatornavaltas
>     -user pattern nem case sensitive
